# Generated by Django 5.0.7 on 2024-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_quotationmodel_asddate_quotationmodel_asdno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcodemodel',
            name='CostCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
