# Generated by Django 5.0.7 on 2024-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_costcodemodel_costcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymodel',
            name='PanNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
