# Generated by Django 5.0.7 on 2024-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_partymodel_panno'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicercmodel',
            name='LCode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
