# Generated by Django 5.0.7 on 2024-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_invoicercmodel_lcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicercmodel',
            name='LCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
